language: rust
rust:
  - 1.15.0
  - 1.15.1
  - 1.16.0
  - stable
before_install:
  - curl -L -o /tmp/consul.zip https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
  - unzip /tmp/consul.zip
  - ./consul agent -config-file data/consul-test.json > /tmp/consul.log &
script:
  - cargo build -v
  - sh data/register.sh
  - cargo test -v
  - cargo doc -v
