language: rust
env:
  global:
    - secure: K2ha5d9/HImWea7AvyotXigPl5QmQ9sENSzzjjn+cIWOOMOpzKgoCH6BknsknLGaacIZ8OIOyId/f3ta9WgCwsibhxHxFjsod8pKSEXuVrbF2BBPjgnyK91tZVG14V8EKc3tosr5RTEGuW9kk9bZCxEftDlRx7l4XCBr48pzYRM=
before_install:
  - curl -L -o /tmp/consul.zip https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
  - unzip /tmp/consul.zip
  - ./consul agent -config-file data/consul-test.json > /tmp/consul.log &
script:
  - cargo build -v
  - sh data/register.sh
  - cargo test -v
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
