language: rust
before_install:
  - curl -L -o /tmp/consul.zip https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
  - unzip /tmp/consul.zip
  - ./consul agent -config-file data/consul-test.json > /tmp/consul.log &
script:
  - cargo build -v
  - sh data/register.sh
  - cargo test -v
