[package]

name = "consul"
version = "0.0.4"
authors = ["YoungKing <yanckin@gmail.com>"]
description = "Rust client libray for Consul HTTP API"
documentation = "http://youngking.github.io/consul-rust/consul/"
repository = "https://github.com/youngking/consul-rust"
license = "MIT"

readme = "README.md"
keywords = ["consul", "discovery"]

exclude = [
    "data/*",
]

[dependencies]
curl = "^0.2"
rustc-serialize = "0.3.15"
