[package]

name = "consul"
description = "Rust client libray for Consul HTTP API"
repository = "https://github.com/youngking/consul-rust"
version = "0.0.2"
license = "MIT"
authors = ["YoungKing <yanckin@gmail.com>"]
keywords = ["consul", "discovery"]

exclude = [
    "data/*",
]

[dependencies]
curl = "0.2.10"
rustc-serialize = "0.3.15"
