[package]

name = "consul"
version = "0.1.0"
authors = ["Andrew Useckas <andrew.useckas@threat-x.com>", "Stu Small <stuart.small@threat-x.com>", "YoungKing <yanckin@gmail.com>"]
description = "Rust client libray for Consul HTTP API"
documentation = "https://github.com/stusmall/consul-rust"
repository = "https://github.com/stusmall/consul-rust"
license = "MIT"

readme = "README.md"
keywords = ["consul", "discovery"]

exclude = [
    "data/*",
]

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
hyper = "^0.10"
hyper-openssl = { git="https://github.com/sfackler/hyper-openssl" }
openssl = "^0.9"
